{
 "title": "Fcity2",
 "time": { "from": "2019-05-24T16:22:05.974Z", "to": "2019-05-24T16:29:59.383Z" },
 "templating": {
  "list": [
   {
    "name": "moyenne",
    "label": "Moyenne sur n valeurs",
    "query": "5,10,30,60,120,300,600,1800,3600"
   },
   {
    "name": "ride_id",
    "label": "Identifiant du trajet",
    "query": "SELECT id FROM ride WHERE start_date IS NOT NULL OR end_date IS NOT NULL"
   }
  ]
 },
 "panels": [
  {
   "title": "Puissance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\nCASE\n  WHEN MIN(d.value) = 0 THEN 0\n  ELSE EXP(SUM(LN(ABS(d.value))))\nEND \"Puissance\", $__time(d.added_on)\nFROM data as d\nJOIN measure as m ON m.id = d.measure_id\nWHERE (m.name = \"voltage\" or m.name = \"intensity\") AND d.ride_id IN (${ride_id:csv}) AND $__timeFilter(d.added_on)\nGROUP BY time_sec"
    },
    {
     "rawSql": "SELECT AVG(puissance.valuepuissance) AS \"Puissance moyenne sur $moyenne valeurs\", $__timeGroupAlias(puissance.added_on, [[moyenne]]s) \nFROM \n(\n\tSELECT\n  CASE\n    WHEN MIN(d.value) = 0 THEN 0\n    ELSE EXP(SUM(LN(ABS(d.value))))\n  END valuepuissance, d.added_on as added_on\n\tFROM data as d \n\tJOIN measure as m ON m.id = d.measure_id \n\tWHERE (m.name = \"voltage\" or m.name = \"intensity\") AND d.ride_id IN (${ride_id:csv})\n\tGROUP BY d.added_on\n) as puissance\nWHERE $__timeFilter(puissance.added_on)\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Vitesse",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    {
     "rawSql": "SELECT value as \"Vitesse\", $__time(d.added_on)\nFROM data as d\nJOIN measure as m ON m.id = d.measure_id\nWHERE m.name = \"speed\" AND d.ride_id IN (${ride_id:csv}) AND $__timeFilter(d.added_on)"
    },
    {
     "rawSql": "SELECT AVG(vitesse.value) AS \"Vitesse moyenne sur $moyenne valeurs\", $__timeGroupAlias(vitesse.added_on, [[moyenne]]s) \nFROM \n(\n\tSELECT value, d.added_on as added_on\n\tFROM data as d \n\tJOIN measure as m ON m.id = d.measure_id \n\tWHERE m.name = \"speed\" AND d.ride_id IN (${ride_id:csv})\n) as vitesse\nWHERE $__timeFilter(vitesse.added_on)\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Eclairement",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "lux" }
   ],
   "targets": [
    {
     "rawSql": "SELECT value as \"Eclairement 1\", $__time(d.added_on)\nFROM data as d\nJOIN measure as m ON m.id = d.measure_id\nWHERE m.name = \"lux1\" AND d.ride_id IN (${ride_id:csv}) AND $__timeFilter(d.added_on)"
    },
    {
     "rawSql": "SELECT AVG(eclairement1.value) AS \"Eclairement 1 moyen sur $moyenne valeurs\", $__timeGroupAlias(eclairement1.added_on, [[moyenne]]s) \nFROM \n(\n\tSELECT value, d.added_on as added_on\n\tFROM data as d \n\tJOIN measure as m ON m.id = d.measure_id \n\tWHERE m.name = \"lux1\" AND d.ride_id IN (${ride_id:csv})\n) as eclairement1\nWHERE $__timeFilter(eclairement1.added_on)\nGROUP BY time"
    },
    {
     "rawSql": "SELECT value as \"Eclairement 2\", $__time(d.added_on)\nFROM data as d\nJOIN measure as m ON m.id = d.measure_id\nWHERE m.name = \"lux2\" AND d.ride_id IN (${ride_id:csv}) AND $__timeFilter(d.added_on)"
    },
    {
     "rawSql": "SELECT AVG(eclairement2.value) AS \"Eclairement 2 moyen sur $moyenne valeurs\", $__timeGroupAlias(eclairement2.added_on, [[moyenne]]s) \nFROM \n(\n\tSELECT value, d.added_on as added_on\n\tFROM data as d \n\tJOIN measure as m ON m.id = d.measure_id \n\tWHERE m.name = \"lux2\" AND d.ride_id IN (${ride_id:csv})\n) as eclairement2\nWHERE $__timeFilter(eclairement2.added_on)\nGROUP BY time"
    },
    {
     "rawSql": "SELECT value as \"Eclairement 3\", $__time(d.added_on)\nFROM data as d\nJOIN measure as m ON m.id = d.measure_id\nWHERE m.name = \"lux3\" AND d.ride_id IN (${ride_id:csv}) AND $__timeFilter(d.added_on)"
    },
    {
     "rawSql": "SELECT AVG(eclairement3.value) AS \"Eclairement 3 moyen sur $moyenne valeurs\", $__timeGroupAlias(eclairement3.added_on, [[moyenne]]s) \nFROM \n(\n\tSELECT value, d.added_on as added_on\n\tFROM data as d \n\tJOIN measure as m ON m.id = d.measure_id \n\tWHERE m.name = \"lux3\" AND d.ride_id IN (${ride_id:csv})\n) as eclairement3\nWHERE $__timeFilter(eclairement3.added_on)\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Accélération",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "accG" }
   ],
   "targets": [
    {
     "rawSql": "SELECT value as \"Accélération\", $__time(d.added_on)\nFROM data as d\nJOIN measure as m ON m.id = d.measure_id\nWHERE m.name = \"acceleration\" AND d.ride_id IN (${ride_id:csv}) AND $__timeFilter(d.added_on)"
    },
    {
     "rawSql": "SELECT AVG(acceleration.value) AS \"Accélération moyenne sur $moyenne valeurs\", $__timeGroupAlias(acceleration.added_on, [[moyenne]]s) \nFROM \n(\n\tSELECT value, d.added_on as added_on\n\tFROM data as d \n\tJOIN measure as m ON m.id = d.measure_id \n\tWHERE m.name = \"acceleration\" AND d.ride_id IN (${ride_id:csv})\n) as acceleration\nWHERE $__timeFilter(acceleration.added_on)\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Trajets",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT r.id AS \"Identifiant\", u.nickname AS \"Pseudo\", v.model AS \"Modèle\", v.brand AS \"Marque\", r.start_reservation AS \"Début réservation\", \nr.end_reservation AS \"Fin réservation\", TIMEDIFF(r.end_reservation, r.start_reservation) AS \"Durée réservation\", \nr.start_date AS \"Début trajet\", r.end_date AS \"Fin trajet\", TIMEDIFF(r.end_date, r.start_date) AS \"Durée trajet\"\nFROM ride AS r\nJOIN users AS u ON u.id = r.user_id\nJOIN vehicle AS v ON v.id = r.vehicle_id"
    }
   ]
  },
  {
   "title": "Utilisateurs",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT u.id AS \"Identifiant\", u.nickname AS \"Pseudo\", u.badgeId AS \"Numéro de badge\", COUNT(r.id) AS \"Nombre de trajet(s) réservé(s)\"\nFROM users AS u\nJOIN ride AS r ON r.user_id = u.id\nGROUP BY r.user_id"
    }
   ]
  },
  {
   "title": "Voitures",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT id AS \"Identifiant\", brand AS \"Marque\", model AS \"Modèle\", type AS \"Type\", numberPlate AS \"Plaque d'immatriculation\" FROM vehicle"
    }
   ]
  }
 ]
}